name: My first workflow
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Elixr Employee name
        run: echo "Welcome Nawaz khan"
      - name: Role of Employee
        run: echo "DevOps Engineer"
      
