name: My first workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Elixr Employee name
        run: echo "Welcome Nawaz khan"
      - name: Role of Employee
        run: echo "DevOps Engineer"
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: Introduce your self
        run: echo "Hello I'm Nawaz"
    
    
      
