name: output information
on: workflow_dispatch
env:
  DEVOPS_ENGINEER_NAME: ${{ secrets.DEVOPS_ENGINEER_NAME }}
jobs:
  infor:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
      - name: Output Engineer name
        run: echo $DEVOPS_ENGINEER_NAME
